### ISSUE TITLE
No difference between windows

### ISSUE THREAD

**Issue by stefonarch** [AlexJakeGreen/wayfire-kbdd-plugin#4]
Not sure if I am missing something, but it does nothing, overall the same layout.
```

[input]
xkb_layout = it,de
xkb_options = grp:alt_shift_toggle
xkb_model= pc105
```

**Comment by AlexJakeGreen** [comment]
Config looks good, these my settings - they are the same
```
xkb_layout = pl,ua
xkb_model = pc104
xkb_options = grp:caps_toggle,grp_led:caps
xkb_rules = evdev
```

Did you compile manually or installed via a package manager?
If compiled manually, a good chances the so file installed somewhere under /usr/local but wayfire does not look there until we tell him using the env variable WAYFIRE_PLUGIN_PATH – this is only needed if plugin is compiled manually, outside the package system.

This is an example how I start wayfire from console
```
function start_wayfire {
    exec > /tmp/wayfire.log
    exec 2>&1

    export XCURSOR_SIZE=48
    export GDK_BACKEND=wayland
    export XDG_SESSION_TYPE=wayland
    export XDG_CURRENT_DESKTOP=sway
    export QT_QPA_PLATFORM=wayland
    export MOZ_ENABLE_WAYLAND=1
    export RTC_USE_PIPEWIRE=true
    export QT_FONT_DPI=150

    pactl set-sink-mute @DEFAULT_SINK@ 1
    pactl set-source-mute @DEFAULT_SOURCE@ 1

    export WAYFIRE_PLUGIN_PATH="/usr/local/lib64/wayfire"
    exec /usr/bin/env dbus-run-session -- /usr/bin/wayfire
}
```

What version of wayfire you run? This plugin is tested with tag 0.7.3. If you built from master branch I'm not sure it will work because the master branch may have incompatible API.

**Comment by stefonarch** [comment]
Should have read messages ;)

> Installing src/libkbdd.so to /usr/local/lib/wayfire

All good, copied it to` /usr/lib/wayfire/` and it works like a charm, only missing a keyboard layout indicater on the bar. Thanks!
